version: 0.2
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm run test
  build:
    commands:
      - echo run build commands for more complicated workflows

artifacts:
  files:
    - app.js
    - index.js
    - node_modules/**/*
